### ISSUE TITLE
架构优化相关

### ISSUE THREAD

**Issue by Request2609** [linuxkerneltravel/lmp#111]
#### 背景
lmp项目为用户提供将系统各项指标以dashboard的形式可视化的服务，涉及有业务应用层，数据库持久化层，内核提取指标层，业务应用层主要实现对用户浏览器传过来的请求进行解析和响应，如下图，用户可以请求查看runqlen指标，时间设置为几分钟，提交即可。

lmp后端收到请求，解析出参数，并开协程执行对应的插件，问题就在于这里执行插件的操作是：

```go
func execute(filepath string, collectTime int, exitChan chan bool) {
    defer func() {
        if err := recover(); err != nil {
            zap.L().Error("error in execute routine, err:", zap.Error(err.(error)))
            fmt.Println("error in execute routine, err:", err)
        }
    }()

    cmd := exec.Command("sudo", "python3", filepath)
    cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}

    stdout, err := cmd.StdoutPipe()
    defer stdout.Close()
    go func() {
        scanner := bufio.NewScanner(stdout)
        for scanner.Scan() {
            line := scanner.Text()
            fmt.Println(line)
        }
    }()

    stderr, err := cmd.StderrPipe()
    defer stderr.Close()
    go func() {
        scanner := bufio.NewScanner(stderr)
        for scanner.Scan() {
            line := scanner.Text()
            fmt.Println(line)
        }
    }()

    err = cmd.Start()
    if err != nil {
        zap.L().Error("error in cmd.Start()", zap.Error(err))
        return
    }

    go func() {
        err = cmd.Wait()
        if err != nil {
            zap.L().Error("error in cmd.Wait()", zap.Error(err))
            return
        }
    }()

    ctx, cancel := context.WithTimeout(context.Background(), time.Duration(collectTime)*time.Second)
    defer cancel()

    for {
        select {
        case <-ctx.Done():
            syscall.Kill(-cmd.Process.Pid, syscall.SIGKILL)
            exitChan <- true
            return
        }
    }
}    
```

其中，exec.command函数是启动新的root进程执行插件的。
![\[外链图片转存失败,源站可能有防盗链机制,建议将图片保存下来直接上传(img-WDbxcoe2-1617512212337)(/home/changke/.config/Typora/typora-user-images/image-20210404152604367.png)\]](https://img-blog.csdnimg.cn/20210404205937879.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzQxNjgxMjQx,size_16,color_FFFFFF,t_70)
<p align=middle>目前lmp模块设计</p>

执行完以后还需要回收新创建进程的资源。在高并发的情况下，lmp项目必定不可用，因为创建进程的系统资源开销很重，创建进程过多资源不足时会导致lmp主进程奔溃。其次，就每个软件系统的设计目标而言：低耦合，高内聚，目前这个系统，功能集成了接收并解析请求，响应请求，开子进程执行插件，回收子进程，功能耦合性太高，可扩展性不强。

#### 对于系统协程使用的个人观点：

***协程的应用场景***
![在这里插入图片描述](https://img-blog.csdnimg.cn/2021040421012933.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzQxNjgxMjQx,size_16,color_FFFFFF,t_70)
协程的出现提高了对用户态的业务处理效率，我们有个计算任务，调用某个应用态函数，可以将这个业务扔给协程去处理，然后线程可以继续执行其他业务，能实现不阻塞这个计算任务这块而导致其他业务也停滞。在执行系统调用或者我们lmp项目的exec.command这种必须要开启进程的系统，使用协程基本上是没有发挥协程自身的优势。

#### 解决方案
想过直接将lmp项目由go迁移成python项目，原框架功能设计可以不变，不过插件的形式应该改成线程执行bcc代码的形式。但是python多线程并没有goroutine的效率高，所以不用了。

如下图，简单明了地描述了新系统的架构设计构想：
![在这里插入图片描述](https://img-blog.csdnimg.cn/20210404210149303.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzQxNjgxMjQx,size_16,color_FFFFFF,t_70)
<p align=middle>待评估lmp模块设计</p>

使用流程：
![在这里插入图片描述](https://img-blog.csdnimg.cn/20210404210444795.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzQxNjgxMjQx,size_16,color_FFFFFF,t_70)
- lmp系统主要赋能：接收请求，响应请求，发送参数给pluginserver

- plugin server主要赋能：一个基于python语言实现的服务器，接收用户请求参数，定时执行bcc指标函数，持久化指标数据，定时清理数据库指标数据

#### 优势分析
- 原来lmp项目功能耦合性过高的问题；
- lmp项目开协程主要处理业务逻辑，充分发挥了协程的优势，实现高并发；
- 避免了lmp开过多进程导致系统崩溃的隐患，plugin server可以部署到其他机器，对其他机器进行指标监控分析；
- plugin server执行bcc是交给线程执行，替换了原来插件执行，线程比进程更加轻量级，没有占用更多的系统资源；
- 对于GitHub上CI的效率会提升。

**Comment by helight** [comment]
想法是不错的，但是我们还有几个点需要考虑：
1.目前是只支持bcc，未来希望还能支持纯bpf，gobpf等其它类型的插件，有可能还有非bpf插件，需要抽象这一层，但是不一定非要以独立服务和python开发，单体服务目前对我们来说更合理，未来在分布式架构中是要做一定拆分的，但是整体服务不能引入多种框架开发语言，这对开发门槛要求比较高。
2.目前的bpf内核程序和用户数据采集程序是放到一起的，未来希望是能在这里做个一拆分，内核程序专做内核程序的事情，用户态数据采集程序可以相对独立，对接内核数据采集和数据用户态存储以及展示服务。
3.插件状态信息管理，目前单机版本中还缺失插件状态信息采集，要能够感知到有哪些bpf程序已经加载到内核，可以感知它的收集数据map，可以读取收集的数据到另外的用户态存储，可以卸载等，这方面也是非常需要的。
4.作为一个管理端系统bcc的编译性能目前不是最重要的，而是管理的合理性和便捷性。对性能要求主要是开发的bpf程序在内核中的性能，这是一个强需求，必经加载只需要一次，但是内核中的执行可能是很高评率的事情。所以目前go协程是足够处理。
5.但是对lmp中的各个模块还是要做抽象分离，但是这种分离可以是面向对象的抽象分离，而不是独立为不通的进程，我们希望是进程内调用，而不是进程间调用。一方面会有一些调用损耗，但这不是主要问题，主要问题是系统的部署复杂性和问题排查复杂性高了很多，日志查看也不方便，类似的问题还很多。所以希望是在这里可以做更多抽象设计，但是还是要以单体架构的形式存在。未来在做分布式的时候也是一个模块以master和slaver模式启动就好了。

**Comment by LinkinPF** [comment]
@helight 大师兄我们目前还是按照上次会议说的方向做，我和@Request2609 沟通完一些点确实是可以优化的，更多是分布式场景下的优化点，性能开销主要还是在ebpf程序上面，优化点后面可以再深入考虑。感谢@helight @Request2609 ^v^

**Comment by Request2609** [comment]
要是以后要将插件的语言迁移为全gobpf的话，确实会避免开进程执行插件的开销。不过要是以后插件还是基于bcc的话，因为lmp要开进程执行插件，对系统的资源消耗还是不能忽视的，我主要考虑开个python服务，可以开线程执行这些bcc代码，这样对系统的资源能进行合理地使用。并且现在lmp系统还有个问题就是，执行插件完成后，还要回收资源，然后才会相应浏览器，比如我要请求进程队列长度的指标，获取1分钟的数据，传到后台后，后台执行1min的插件，然后杀掉插件进程回收资源，最后才返回前端响应页面。这一点在拆分心新服务之后就会被解决，目前框架看样子还比较不好解决。而且拆分服务也不需要增加新语言，还是目前的python和go。其实我的立足点是将执行插件服务拆分出来后，可以更好地对该服务进行扩展，使得整个指标查询系统的功能更加强大，可以实现对数据库中的数据管理，比如设置定时器对数据裤中的数据进行管理，插入删除和修改。可以通过一个lmp查询不同机器上的指标，只需要将执行插件的服务部署到对应的机器上就行，而不是整套lmp系统。lmp相当于一个总的“司令部”，只需要接收用户请求和发送命令给插件服务，而插件服务相当于“下属”，按照要求干活即可。这样系统的分工更加清晰。至于将插件部署到不同的机器我认为并不是分布式的概念，我理解分布式是多个lmp，有主lmp，从lmp等，之间进行联系，分布式主要解决的问题还是系统稳定性，高可用的问题，一个机器当掉了，其他服务机器可以马上替换它。而我们拆分后的插件的部署，是系统功能的扩展，让系统能提供查询更多机器指标的服务。让系统功能强大之后，我们可以就系统的稳定性和高可用，进行分布式部署，这两者并不冲突的！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linuxkerneltravel/lmp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月5日(星期一) 上午8:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [linuxkerneltravel/lmp] 架构优化相关 (#111)





 
想法是不错的，但是我们还有几个点需要考虑：
 1.目前是只支持bcc，未来希望还能支持纯bpf，gobpf等其它类型的插件，有可能还有非bpf插件，需要抽象这一层，但是不一定非要以独立服务和python开发，单体服务目前对我们来说更合理，未来在分布式架构中是要做一定拆分的，但是整体服务不能引入多种框架开发语言，这对开发门槛要求比较高。
 2.目前的bpf内核程序和用户数据采集程序是放到一起的，未来希望是能在这里做个一拆分，内核程序专做内核程序的事情，用户态数据采集程序可以相对独立，对接内核数据采集和数据用户态存储以及展示服务。
 3.插件状态信息管理，目前单机版本中还缺失插件状态信息采集，要能够感知到有哪些bpf程序已经加载到内核，可以感知它的收集数据map，可以读取收集的数据到另外的用户态存储，可以卸载等，这方面也是非常需要的。
 4.作为一个管理端系统bcc的编译性能目前不是最重要的，而是管理的合理性和便捷性。对性能要求主要是开发的bpf程序在内核中的性能，这是一个强需求，必经加载只需要一次，但是内核中的执行可能是很高评率的事情。所以目前go协程是足够处理。
 5.但是对lmp中的各个模块还是要做抽象分离，但是这种分离可以是面向对象的抽象分离，而不是独立为不通的进程，我们希望是进程内调用，而不是进程间调用。一方面会有一些调用损耗，但这不是主要问题，主要问题是系统的部署复杂性和问题排查复杂性高了很多，日志查看也不方便，类似的问题还很多。所以希望是在这里可以做更多抽象设计，但是还是要以单体架构的形式存在。未来在做分布式的时候也是一个模块以master和slaver模式启动就好了。

**Comment by LinkinPF** [comment]
1、不是全部迁移成gobpf，是支持不同类型的ebpf运行方式，比如纯C，bcc，bpftrace、传统工具等等，统一用工厂模式组织。
2、开进程变为开线程是可以减少开销的，是一个优化点，这里还有一个问题就是每一个插件带来的性能开销，可能一次性执行5个，系统开销就会增大很多，系统状态就不支持再开启新的指标了。
3、目前代码没有跳转grafana，使用方法应该是打开lmp页面，再打开grafana，不跳转了，lmp页面只做下发，来回跳转反而不方便。目前正在做指标执行状态。
4、lmp的分布式当然是提取多个节点的性能数据，完全不用实现另外一套逻辑，只用rpc实现节点逻辑就可以了，分布式目前优先级不高。
5、把前端参数处理和执行指标分成两个部分是没问题的，确实是优化点。

**Comment by Request2609** [comment]
嗯，理解了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linuxkerneltravel/lmp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月6日(星期二) 中午1:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [linuxkerneltravel/lmp] 架构优化相关 (#111)





 
1、不是全部迁移成gobpf，是支持不同类型的ebpf运行方式，比如纯C，bcc，bpftrace、传统工具等等，统一用工厂模式组织。
 2、开进程变为开线程是可以减少开销的，是一个优化点，这里还有一个问题就是每一个插件带来的性能开销，可能一次性执行5个，系统开销就会增大很多，系统状态就不支持再开启新的指标了。
 3、目前代码没有跳转grafana，使用方法应该是打开lmp页面，再打开grafana，不跳转了，lmp页面只做下发，来回跳转反而不方便。目前正在做指标执行状态。
 4、lmp的分布式当然是提取多个节点的性能数据，完全不用实现另外一套逻辑，只用rpc实现节点逻辑就可以了，分布式目前优先级不高。
 5、把前端参数处理和执行指标分成两个部分是没问题的，确实是优化点。
