### ISSUE TITLE
修改BCC程序之参数如何处理

### ISSUE THREAD

**Issue by netpy** [linuxkerneltravel/lmp#128]
bcc程序一般都有很多参数，在运行时可以根据需要指定，从而输出不同的结果，这些参数发改分为几类：

- 指定运行时间和输出间隔；
- 对输出结果分类：比如offcputime程序，指定-k输出内核进程的栈阻塞时间，-u输出用户进程的栈阻塞时间；
- 指定跟踪粒度：比如offcputime，默认追踪系统上所有进程的栈阻塞时间，-p则可以指定跟踪某一个进程；
- 等等...

在修改bcc程序时该如何处理这些参数，有如下解决方案：

1. 仅保留默认参数，这种方式不需要修改现有的后端代码；
2. 支持所有的三叔，这种方式首先需要修改前下发指标页面，后端可能也要做相应修改，数据展示页面则要根据对应的输出进行展示，这要求数据展示部分要非常灵活，因为不同的参数其输出结果可能不同，要做相应的处理；
3. 保留一部分，删除一部分，这种方式是一种折中，牺牲一部分工具的优势，缓解数据展示部分对灵活性的要求。

大家可以发表自己的看法，在接下来该指标的过程中做成一个标准，方便大家改指标。

**Comment by LinkinPF** [comment]
对的，目前项目全是全局性的指标，后续肯定需要pid过滤，以及类似于每事件输出还是每段时间间隔输出。
1. 指标提取时间由前端页面下发配置，go web层面管理，减少插件中时间管理代码。
2. 统一脚本的不同指标这块，我目前主要考虑指标模板的通用性，也就是首先保证模板的统一，在考虑怎么组织不同的指标输出。
3. pid过滤和每事件输出还是每段时间间隔输出这块首先是前端页面下发配置，后端代码只把参数下发给模板，尽量避免后端代码会随着插件代码变动
