### ISSUE TITLE
lmp物理机安装

### ISSUE THREAD

**Issue by netpy** [linuxkerneltravel/lmp#184]
lmp在物理机（实验室服务器）上安装的过程中遇到了一些问题：
1.在config.yaml中mysql的密码是123456，如果本机所安装mysql的密码不是123456，需要将config.yaml中的mysql密码改为自己的密码；
2.使用docker安装influxdb时，默认pull的镜像是最新的，但是运行readme中的docker run命令之后，在influxdb中并没有成功安装influxdb或者说influxdb是无法正常工作的。具体原因未知，但是将镜像版本降低之后这个问题就解决了，我使用的镜像版本是1.8：
相应的命令为：
```
sudo docker pull influxdb:1.8
 sudo docker run -d \
    -p 8083:8083 \
    -p 8086:8086 \
    --name influxdb \
    -v ${YOUR_PROJECT_PATH}/lmp/test/influxdb_config/default.conf:/etc/influxdb/influxdb.conf \
    -v ${YOUR_PROJECT_PATH}/lmp/test/influxdb_config/data:/var/lib/influxdb/data \
    -v ${YOUR_PROJECT_PATH}/lmp/test/influxdb_config/meta:/var/lib/influxdb/meta \
    -v ${YOUR_PROJECT_PATH}/lmp/test/influxdb_config/wal:/var/lib/influxdb/wal influxdb:1.8
```

**Comment by chenamy2017** [comment]
第一个问题需要在readme中说明，可以专门可以增加一节数据库安装配置说明
第二个问题，具体原因如果能定位到是因为influxdb版本引起的问题，那么可以在readme中说明支持的infuxdb的版本。docker本身不是必须项。

**Comment by StLeoX** [comment]
新增docker-compose.yml配置
