### ISSUE TITLE
挂载函数点失败

### ISSUE THREAD

**Issue by Teanix** [linuxkerneltravel/lmp#207]
Traceback (most recent call last):
  File "huge.py", line 35, in <module>
    b.attach_kprobe(event="do_page_fault", fn_name="do_return")
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 803, in attach_kprobe
    raise Exception("Failed to attach BPF program %s to kprobe %s" %
Exception: Failed to attach BPF program b'do_return' to kprobe b'do_page_fault'

**Comment by LinkinPF** [comment]
内核版本是哪个？

**Comment by Teanix** [comment]
5.4.0-47

**Comment by WuXianChangKuang** [comment]
一般情况下，可以探测内核中的任何函数，包括中断处理函数。不过在kernel/kprobes.c和arch/*/kernel/kprobes.c程序中用于实现kprobes自身的函数是不允许被探测的，另外还有do_page_fault和notifier_call_chain；
不过可以使用PERF.PERF_TYPE_SOFTWARE.PAGE_FAULTS。
