### ISSUE TITLE
lmp插件管理问题

### ISSUE THREAD

**Issue by JiaoTuan** [linuxkerneltravel/lmp#208]
# 问题1:plugins/db_writer/bufferImpl.py文件包引导问题，我使用相对路径也还是这个报错，只能将路径写死
![image1](https://user-images.githubusercontent.com/67968158/141468130-a56b86fc-a316-480c-a215-0ec7d0a85786.png)
# 问题2：plugins/db_writer/writerImpl.py未找到settings包
![image2](https://raw.githubusercontent.com/JiaoTuan/Images-JiaoTuan/master/kernel_net/问题2.382c3mo4uyg0.png)
# 问题三：将虚拟机挂起再打开就会出现该错误，只能重启虚拟机解决
![image3](https://raw.githubusercontent.com/JiaoTuan/Images-JiaoTuan/master/kernel_net/问题3.54joeircvyo0.png)

**Comment by helight** [comment]
已经修复了 https://github.com/linuxkerneltravel/lmp/pull/216
