### ISSUE TITLE
lmp启动问题

### ISSUE THREAD

**Issue by FIXoo2** [linuxkerneltravel/lmp#209]
# 问题：在首页下发指令后报错。
![image-20211115161332754](https://i.loli.net/2021/11/15/VePGYWnoukbHsQd.png)

**Comment by helight** [comment]
# -*- coding: utf-8 -*-

所有的python 文件都在头顶加一下文件编码方式，我们统一使用utf-8

**Comment by helight** [comment]
``` python
#!/usr/bin/env python
# -*- coding:utf-8 -*-

# 下面是正式代码
```

**Comment by helight** [comment]
这个问题已经解决了
