### ISSUE TITLE
plugins整理

### ISSUE THREAD

**Issue by helight** [linuxkerneltravel/lmp#210]
plugins中的文件进行梳理：把这个目录中的文件进行梳理归类
初步梳理：
common：公共库
cpu：
fs：
net：
。。。。

**Comment by helight** [comment]
@Teanix 这部分代码怎么样了

**Comment by Teanix** [comment]
师兄 这部分工作是纪庆在做

**Comment by netpy** [comment]
该工作已经完成，已提交PR。
