### ISSUE TITLE
grafana无法连接到influxdb

### ISSUE THREAD

**Issue by byxzone** [linuxkerneltravel/lmp#212]
![WX20211119-104124@2x Medium](https://gitee.com/barryx/kernel_study/raw/master/img/202111191043518.jpeg)

grafana连接influxdb时显示`failed to fetch`

（连接的用户名、密码为root、123456，与config.yaml中一致）

![WX20211119-104153@2x](https://gitee.com/barryx/kernel_study/raw/master/img/202111191044247.png)

docker运行状态

**Comment by helight** [comment]
https://grafana.com/docs/grafana/latest/datasources/influxdb/
参考一下这里的文档

**Comment by byxzone** [comment]
在docker里连接到grafana的/bin/bash里，使用wget访问localhost:8086显示连接失败，通过域名访问 [域名:8086]显示404，也就是可以连接到。然后再grafana配置里把地址改成了 [域名:8086]就可以连接了。因为我是在云ECS上配置的，不太清楚是云ECS的问题还是docker隔离机制的问题。

**Comment by helight** [comment]
👍，还可以继续总结
