### ISSUE TITLE
嵌入式轻量级的ebpf移植

### ISSUE THREAD

**Issue by shiqi-linux** [linuxkerneltravel/lmp#243]
有没有做过嵌入式轻量级的ebpf移植？没有clang和llvm的情况下，直接使用libbpf.a的方法。

**Comment by LinkinPF** [comment]
您好，很高兴看到您的 issue

我本人没有这方面的实际项目经验，我自己的理解是嵌入式设备执行 BPF ：
1. 内核选项支持 CONFIG_DEBUG_INFO_BTF=y
2. 可增加 libbpf.a 静态库
3. libbpf 在设计的时候就有考虑在硬件资源紧张的嵌入式设备上执行的场景，所以把静态库和 BPF 的 ELF 上传执行是可行的

如果使用的内核版本没有支持 CONFIG_DEBUG_INFO_BTF=y 选项或者希望更进一步减小 BPF ELF 文件的大小，可以考虑使用 bpftool 的 BTFGen 功能，该功能是为了解决没有支持 CONFIG_DEBUG_INFO_BTF=y 选项（老版本）内核的可移植性问题，它是目前的临时过渡解决方案，会有一些限制，最终的解决办法仍然是采用较新的内核版本支持 CONFIG_DEBUG_INFO_BTF=y 选项。

如果具体的生产环境有特殊的限制可能也会影响 BPF ELF 的执行，例如是否可以获取 root 权限等。

希望可以帮助到您 ^ ^

**Comment by LinkinPF** [comment]
Linux 内核之旅社区有小伙伴回复：

可以spike下 ply 项目，号称只依赖于 libc。

**Comment by shiqi-linux** [comment]
非常感谢
找到链接：https://github.com/wkz/ply
我在我设备上研究下

**Comment by shiqi-linux** [comment]
ply v1.x可以在设备上使用
2.x 由于内核版本问题，没有编译成功，还需要研究下

close
