### ISSUE TITLE
[FEATURE] 为 LMP 添加 eBPF Hub 的命令行工具

### ISSUE THREAD

**Issue by yunwei37** [linuxkerneltravel/lmp#380]
**Is your feature request related to a problem? Please describe.**

# LMP eBPF Store Design

### 1.1. 关于 LMP 项目

- 面向 ePF 初学者和爱好者，提供 eBPF 学习资料、程序/项目案例，构建 eBPF 学习社区
- 成为 eBPF 工具集散地，我们相信每一位 eBPF 初学者和爱好者都有无限的创造力
- 孵化 eBPF 想法、相关工具、项目

个人感觉 LMP 当前可能存在的一些问题或痛点：

- 对于初学者：Supermarket 里面每个子项目的文档都是独立的，目前还没有很好的整合起来；进行查找、搜索、索引很困难；
- 对于 eBPF 工具的开发者：存在非常多而且复杂的用户态可视化、展示方案，有许多套系统提供可视化的实现并且有多种语言混合，缺乏展示标准、难以进行可视化的整合；
- 对于贡献者：作为开源项目，缺少一个提供贡献的指导手册，虽然参与开源的成本较低（把项目上传就行），但是项目的复杂度、混乱度可能会随之上升；

### 1.2. 关于 eBPF 生态

现有的 eBPF 生态可能有存在两个方面的问题：

1. 一方面，对于新手而言，搭建和开发 ebpf 程序是一个门槛比较高、比较复杂的工作，必须同时关注内核态和用户态两个方面的交互和信息处理
2. 另一方面，个人编写的 ebpf 程序很难不通过 review 直接添加到 bcc 这样的大型的工具集中，使用或者集成个人开发者编写的 ebpf 程序也是一个很困难工作:

   - 它们可能使用多种用户态语言开发（go，rust，c/cpp 等等），有各种各样不同的接口;
   - 没有编译好的二进制程序，必须自己配置环境和编译才能使用；
   - 没办法很轻松以插件的方式集成到大型的可观测性或其他系统中，一般必须修改代码并重新编译整个可观测性的框架然后部署上线，才能更新其中的 bpf 探针；

总而言之：eBPF 缺少对于新手友好的开发方案，缺少一个 eBPF 工具通用的分发和托管平台，类似于 github 或者 docker hub。

## 2. 项目目标

基于上述的背景，我们希望有如下的两个部分：

1. 提供一个通用、规范化的 eBPF 程序/应用插件/工具的托管平台或应用商店，以及包管理器，可以在本地一行命令拉下来即可启动，不需要配置管理环境和重新编译并且通过 exporter 获得可视化信息；
2. 提供前端界面，提供对 LMP 里面所有 eBPF 工具的介绍和索引，帮助其他人检索和查找 eBPF 程序；

规范化的 eBPF 程序应当具有如下特征：

- `可移植`：让 eBPF 工具和应用完全平台/架构无关、可移植，不需要进行重新编译即可以跨平台/跨架构分发，不局限于内核版本，使用者本地无需任何 eBPF 相关环境配置；
- `隔离性`： eBPF 程序的加载和执行、以及用户态的数据处理流程应安全可靠；可以在大型的应用中作为可观测性插件使用，不会影响其他项目本身；
- `跨语言`：允许各种背景的开发人员（C、Go、Rust、Java、TypeScript 等）用他们选择的语言编写 eBPF 的用户态程序，而不需要学习新的语言；
- `轻量级`：包的数量和大小尽量小，启动速度尽可能快，本地安装的二进制尽可能小，不需要其他依赖；

包管理器是一个命令行工具，前端是一个网页，二者可以完全独立运行，不存在依赖关系。只是前端界面中有命令行工具的相关介绍文档，以及运行 eBPF 程序的一行命令。

对于编写 eBPF 代码的新手来说，应该可以屏蔽底层的实现方式，用户态如果需要编写一些代码的话，也应当是用他们熟悉的语言，不需要了解底层的编译流程。

### 项目成果

1. 一个或一些命令行工具，作为包管理器、编译和运行 eBPF 程序的工具；用来简化 eBPF 程序的分发、使用，和新手的编写过程；
2. 一个网页，作为前端界面; 用来解决 LMP 的问题，同时用来搜索；
3. 一个服务端，用来发布和下载编译好的 eBPF 程序; 用来托管 eBPF 程序；

**Describe the solution you'd like**

### 5.1. 结合 eBPF 和 WASM

一般来说，一个完整的 eBPF 应用程序分为用户空间程序和内核程序两部分：

- 用户空间程序负责加载 BPF 字节码至内核，或负责读取内核回传的统计信息或者事件详情，进行相关的数据处理和控制；
- 内核中的 BPF 字节码负责在内核中执行特定事件，如需要也会将执行的结果通过 maps 或者 perf-event 事件发送至用户空间

用户态程序可以在加载 eBPF 程序前控制一些 eBPF 程序的参数和变量，以及挂载点；也可以通过 map 等等方式进行用户态和内核态之间的双向通信。那么，如果将用户态的所有控制和数据处理逻辑全部移到 WASM 虚拟机中，通过 WASM module 打包和分发 eBPF 字节码，同时在 WASM 虚拟机内部完成整个 eBPF 程序的加载和执行，也许我们就可以将二者的优势结合起来，让任意 eBPF 程序能有如下特性：

- `可移植`：让 eBPF 工具和应用完全平台无关、可移植，不需要进行重新编译即可以跨平台分发；
- `隔离性`：借助 WASM 的可靠性和隔离性，让 eBPF 程序的加载和执行、以及用户态的数据处理流程更加安全可靠；事实上一个 eBPF 应用的用户态控制代码通常远远多于内核态；
- `包管理`：借助 WASM 的生态和工具链，完成 eBPF 程序或工具的分发、管理、加载等工作，目前 eBPF 程序或工具生态可能缺乏一个通用的包管理或插件管理系统；
- `跨语言`：目前 eBPF 程序由多种用户态语言开发（如 Go\Rust\C\C++\Python 等），超过 30 种编程语言可以被编译成 WebAssembly 模块，允许各种背景的开发人员（C、Go、Rust、Java、TypeScript 等）用他们选择的语言编写 eBPF 的用户态程序，而不需要学习新的语言；
- `敏捷性`：对于大型的 eBPF 应用程序，可以使用 WASM 作为插件扩展平台：扩展程序可以在运行时直接从控制平面交付和重新加载。这不仅意味着每个人都可以使用官方和未经修改的应用程序来加载自定义扩展，而且任何 eBPF 程序的错误修复和/或更新都可以在运行时推送和/或测试，而不需要更新和/或重新部署一个新的二进制；
- `轻量级`：WebAssembly 微服务消耗 1% 的资源，与 Linux 容器应用相比，冷启动的时间是 1%：我们也许可以借此实现 eBPF as a service，让 eBPF 程序的加载和执行变得更加轻量级、快速、简便易行；

我们目前已经有一个将 eBPF 和 WASM 结合起来的，可行性验证性质的项目，之后可能会在这个基础上继续构建：eunomia-bpf 是 `eBPF 技术探索 SIG` [3] [5] 中发起并孵化的项目，目前也已经在 [github](https://github.com/eunomia-bpf/eunomia-bpf) [4] 上开源。eunomia-bpf 是一个 eBPF 程序的轻量级开发加载框架，包含了一个用户态动态加载框架/运行时库，以及一个简单的编译工具链。eunomia-bpf 的目标是让 eBPF 程序的开发、加载和执行变得更加简单、轻量级、快速、可靠、安全、可移植、敏捷、跨语言、可扩展等。只需要编写 eBPF 程序的内核态代码，以 JSON 的形式分发和使用编译后的 eBPF 代码，就可以跨平台、跨内核版本自动获得上报的事件。也可以以 WASM module 的方式，将内核态和用户态的代码一同进行分发，在目标机器上动态加载运行。

WASM 的所有复杂度都会被隐藏起来，实际上用户可以不知道自己开发的用户态程序会被编译为 WASM 模块并进行分发。

### 包管理器命令行工具

- 复用 ecli 和 docker 的成果，只需要关注如何获得正确的 ebpf 程序的下载地址，然后把它交给 ecli 就行。编译模板生成也是一样，底层会去调用 ecli 的相关命令。
- 可以先不关注登录和上传的过程，采用 Github PR 或者 gitee PR 的形式提交新的 eBPF 程序。

## 命令行启动器具体设计

我们需要一个 LMP 的命令行启动器，去调用 ecli 的相关命令：；

### 使用者

首先，我们有一个开发人员的用例，他想使用 ebpf 二进制文件或者程序，但不知道如何/在哪里找到它:

直接运行

```console
$ lmp run opensnoop                                                     # 使用一个名字直接跑起来，如果本地没有，就去网上对应的 repo 下载
running and waiting for the ebpf events from perf event...
$ lmp run opensnoop:latest                                              # 使用一个名字和版本号
running and waiting for the ebpf events from perf event...
$ lmp run https://github.com/ebpf-io/raw/master/examples/opensnoop/app.wasm # 使用一个http API
running and waiting for the ebpf events from perf event...
$ lmp run ./opensnoop/package.json                                               # 使用一个本地路径
running and waiting for the ebpf events from perf event...
$ lmp run sigsnoop -h                                                  # 带参数
Usage: sigsnoop [-h] [-x] [-k] [-n] [-p PID] [-s SIGNAL]
Trace standard and real-time signals.


    -h, --help  show this help message and exit
    -x, --failed  failed signals only
    -k, --killed  kill only
    -p, --pid=<int>  target pid
    -s, --signal=<int>  target signal
```

run 命令实际上包含了 pull 命令，如果本地没有对应的 ebpf 文件，就会去网上下载，如果本地有，就直接使用本地的：

```console
$ lmp pull opensnoop
$ lmp run opensnoop
running and waiting for the ebpf events from perf event...
```

或者他/她也可以在网页上进行搜索，然后直接下载（具体查看下章）.

可以切换源，比如从 github 切换到 lmp 静态服务器:

```console
LMP_REPOSITORY=https://lmp.ebpf.io lmp run opensnoop # 从 lmp 静态服务器下载，前缀路径改为 https://lmp.ebpf.io
```

ecli 已经实现了相关的功能，包括 run 和 pull，只需要有个启动器在 lmp run 的时候去命令行调用 ecli:

lmp run xxx 可以等价于
```
sudo EUNOMIA_REPOSITORY=https://linuxkerneltravel.github.io/lmp/ EUNOMIA_HOME=/home/ubuntu/.lmp/ ./ecli run xxx
```

lmp pull xxx 可以等价于
```
sudo EUNOMIA_REPOSITORY=https://linuxkerneltravel.github.io/lmp/ EUNOMIA_HOME=/home/ubuntu/.lmp/ ./ecli pull xxx
```

其他同理。LMP 的命令行里面只需要去执行对应的命令，类似于 C 语言使用 system("ecli run xxx") 这样。

### 开发人员

我们的第二个角色是一个开发人员，他想要创建一个通用 eBPF/WASM 预编译二进制，并在任何机器和操作系统上分发它，并且动态加载运行。这对于命令行工具或者可以直接在 Shell 中运行的任何东西都很有用，也可以作为大型项目的插件使用。

生成 ebpf 数据文件

```bash
$ lmp init opensnoop  # 生成一个项目模板
init project opensnoop success.
$ cd opensnoop  # 会创建一个新的目录
$ ls # 生成如下一些文件
opensnoop.bpf.c opensnoop.bpf.h README.md config.json .gitignore
$ lmp build # 构建内核态程序
$ ls # 生成如下一些文件，package.json 是编译生成的产物
opensnoop.bpf.c opensnoop.bpf.h README.md config.json package.json .gitignore
$ lmp gen-wasm-skel # 生成 wasm 用户态项目模板
make
  GENERATE_PACKAGE_JSON
  GEN-WASM-SKEL
$ ls # 生成如下一些文件
app.c eunomia-include ewasm-skel.h package.json README.md  opensnoop.bpf.c  opensnoop.bpf.h
$ lmp build-wasm
make
  GENERATE_PACKAGE_JSON
  BUILD-WASM
build app.wasm success
$ lmp run app.wasm -h
Usage: opensnoop [-h] [-x] [-k] [-n] [-p PID]
```

我们提供的是 C 语言版本的 WASM 开发框架，它包含如下这些文件：

- ewasm-skel.h：用户态 WebAssembly 开发框架的头文件，包含了预编译的 eBPF 程序字节码，和 eBPF 程序框架辅助信息，用来动态加载；
- eunomia-include：一些 header-only 的库函数和辅助文件，用来辅助开发；
- app.c：用户态 WebAssembly 程序的主要代码，包含了 eBPF 程序的主要逻辑，以及 eBPF 程序的数据处理流程。

其中 app.c 中用户需要编写的代码应该是纯粹的、正常的 C 语言代码，不需要有任何关于底层 WASM 实现的知识。可以在完全对 WASM 不了解的情况下，使用我们提供的框架进行开发。

其中：
- lmp build 等价于 
```
docker run -it -v `pwd`/:/src/ yunwei37/ebpm:latest 
```
- lmp init hello-world 等价于 
```
git clone https://github.com/eunomia-bpf/ebpm-template && mv ebpm-template hello-world
```
- lmp gen-wasm-skel 等价于 
```
docker run -it -v `pwd`/:/src/ yunwei37/ebpm:latest gen-wasm-skel
```

以此类推。上面 ecli 和 docker 的这些命令都已经实现了，就是需要一个命令行的包装和启动器，去隐藏起来底下调用命令的一个复杂度。

### 安装 LMP

lmp 的 cli 还需要一个安装脚本，帮助用户选择正确的架构，下载 ecli 和 docker 镜像，并且添加到 path 里面。类似这样：

```
curl -sL https://lmp/xxx/install | sh
```

它会完成类似这样的操作：

```console
$ # download the release from https://github.com/eunomia-bpf/eunomia-bpf/releases/latest/download/ecli
$ wget https://aka.pw/bpf-ecli -O /usr/bin/ecli && chmod +x /usr/bin/lmp
$ docker pull yunwei37/ebpm:latest
$ wget http://lmp/releases/latest/download/lmp -O /usr/bin/lmp && chmod +x /usr/bin/lmp
```

命令可能不一定准确，大概是这个意思，可以参考这个脚本：https://raw.githubusercontent.com/solo-io/bumblebee/main/install_cli.sh

## 参考资料

我们希望使用起来类似这样的效果：https://www.solo.io/blog/get-started-with-ebpf-using-bumblebee/

- eunomia-bpf 仓库：https://github.com/eunomia-bpf/eunomia-bpf
- ecli 的相关实现：https://github.com/eunomia-bpf/eunomia-bpf/blob/master/ecli
- ecli 和 wasm 的介绍：https://mp.weixin.qq.com/s/ryT7OqWngCjcCkfeSKjutA
- 有点过时的 eunomia-bpf 文档：https://openanolis.cn/sig/ebpfresearch/doc/646023027267993641

**Comment by yunwei37** [comment]
有哪位愿意完成这样的项目，可以留言一下 : )

（其实我估计这个实现起来应该很容易，就是命令行解析一下参数再调不同的命令就好x

**Comment by GorilaMond** [comment]
我可以帮忙做一下😀

**Comment by yunwei37** [comment]
也想问一下，这个命令行启动器的项目合并到哪里去会比较好呢？

其实我建议是在 linuxkerneltravel 里面新建一个 lmp-cli 项目（类似于 lmp_doc 一样），然后做完这部分把它合并到那个仓库里面。LMP 这个主仓库本身应该放各种各样的 eBPF 小工具或者 submodule，如果放在主仓库的话可能会导致主仓库进一步膨胀；维护 cli 的时候也需要把整个 LMP clone 下来再提交。也可以放在另外一个仓库里面，然后把另外一个仓库添加为 lmp 的 submodule，放在 lib 下面。

**Comment by GorilaMond** [comment]
> 也想问一下，这个命令行启动器的项目合并到哪里去会比较好呢？
> 
> 其实我建议是在 linuxkerneltravel 里面新建一个 lmp-cli 项目（类似于 lmp_doc 一样），然后做完这部分把它合并到那个仓库里面。LMP 这个主仓库本身应该放各种各样的 eBPF 小工具或者 submodule，如果放在主仓库的话可能会导致主仓库进一步膨胀；维护 cli 的时候也需要把整个 LMP clone 下来再提交。也可以放在另外一个仓库里面，然后把另外一个仓库添加为 lmp 的 submodule，放在 lib 下面。

好主意欸👍

**Comment by helight** [comment]
> 也想问一下，这个命令行启动器的项目合并到哪里去会比较好呢？
> 
> 其实我建议是在 linuxkerneltravel 里面新建一个 lmp-cli 项目（类似于 lmp_doc 一样），然后做完这部分把它合并到那个仓库里面。LMP 这个主仓库本身应该放各种各样的 eBPF 小工具或者 submodule，如果放在主仓库的话可能会导致主仓库进一步膨胀；维护 cli 的时候也需要把整个 LMP clone 下来再提交。也可以放在另外一个仓库里面，然后把另外一个仓库添加为 lmp 的 submodule，放在 lib 下面。

可以的，动手起来

**Comment by GorilaMond** [comment]
我的demo：[https://github.com/GorilaMond/lmp-startup](url)

**Comment by yunwei37** [comment]
我觉得可以啦！有些细节的小问题，不过总体上是应该可以用了，也许现在就可以在 lmp 里面开个 repo 然后提 pr了?

**Comment by yunwei37** [comment]
接下来就是写篇文章描述一下你的成果，然后还需要一个脚本来帮忙一行命令安装 lmp （类似我上面写的那样，curl 一下就都可以安装，注意 ecli 目前构建的二进制是基于 x86 架构的，如果不是 x86 架构要返回错误，可以用 uname 命令判断是不是 x86 ）

**Comment by GorilaMond** [comment]
> 我觉得可以啦！有些细节的小问题，不过总体上是应该可以用了，也许现在就可以在 lmp 里面开个 repo 然后提 pr了?

好呀，我觉得可以

**Comment by helight** [comment]
https://github.com/linuxkerneltravel/lmp_cli
已经创建repo，跑动起来吧
@GorilaMond @yunwei37

**Comment by helight** [comment]
另外我建议我们使用golang来开发

**Comment by yunwei37** [comment]
这个 issue 应该已经结束啦，之后新的需求会换到新的 issue 里面
