### ISSUE TITLE
[FEATURE] enable push eBPF applications to Github Packages for lmp-cli

### ISSUE THREAD

**Issue by yunwei37** [linuxkerneltravel/lmp#386]
**Is your feature request related to a problem? Please describe.**

see #380

In eBPF hub, The storage has not yet complete, `push` is not implement, and `pull` operation is too simple and sometimes naive (eg. cannot support label)

The other programs in the eBPF supermarket cannot be pull and run as well.

**Describe the solution you'd like**

use oras and oci support for eunomia-bpf packages, and other related packages.

- [ ] add lmp cli or ecli support for push, pull JSON and WASM module to ORAS
- [ ] enable generate wasm module in lmp CI
- [ ] auto push OCI wasm module to storage: can be github packages or others

**Provide usage examples**

```console
$ ./ecli push .ebpm/sigsnoop/app.wasm ghcr.io/linuxkerneltravel/sigsnoop:latest
INFO[0003] Pushed: ghcr.io/linuxkerneltravel/sigsnoop:latest 
INFO[0003] Size: 70076                                  
INFO[0003] Digest: sha256:08b18a1e1386a34ca37b35426a560ad3bef5490de20517397afe6bb872fd050e
$ ./ecli  pull ghcr.io/linuxkerneltravel/sigsnoop:latest
INFO[0002] Pulled: ghcr.io/linuxkerneltravel/sigsnoop:latest 
INFO[0002] Size: 70076                                  
INFO[0002] Digest: sha256:77c5cd43d87c404e81c2a7a941dc80acf68bb4c5b48a301dbb9ed9f87ef4996f 
$ sudo ./ecli run module.wasm                                                                        
load runtime arg: filtered_pid 0
load runtime arg: target_signal 0
load runtime arg: failed_only 
running and waiting for the ebpf events from perf event...
{"pid":1286245,"tpid":1286168,"sig":0,"ret":0,"comm":"node","sig_name":"N/A"}
{"pid":1286168,"tpid":935473,"sig":0,"ret":0,"comm":"node","sig_name":"N/A"}
{"pid":1286168,"tpid":935473,"sig":0,"ret":0,"comm":"node","sig_name":"N/A"}
```

**Additional context**

- https://docs.github.com/cn/packages/working-with-a-github-packages-registry/working-with-the-container-registry
- https://github.com/engineerd/wasm-to-oci
- https://github.com/eunomia-bpf/eunomia-bpf

**Comment by GorilaMond** [comment]
I will do it.
