### ISSUE TITLE
[BUG]get_loadavg.py中报错

### ISSUE THREAD

**Issue by pxp531** [linuxkerneltravel/lmp#560]
**Describe the bug**
myrq.h:23:30: error: use of undeclared identifier 'UCLAMP_BUCKETS'; did you mean 'UCLAMP_CNT'?
        struct uclamp_bucket bucket[UCLAMP_BUCKETS];
                                    ^~~~~~~~~~~~~~
                                    UCLAMP_CNT
include/linux/sched.h:277:2: note: 'UCLAMP_CNT' declared here

**Desktop (please complete the following information):**

* OS: centos7 linux5.4.54.

**Comment by helight** [comment]
eBPF_Supermarket/CPU_Subsystem/BCC_sar/src/cpu_loadavg/get_loadavg.py

**Comment by zhangzihengya** [comment]
> **Describe the bug** myrq.h:23:30: error: use of undeclared identifier 'UCLAMP_BUCKETS'; did you mean 'UCLAMP_CNT'? struct uclamp_bucket bucket[UCLAMP_BUCKETS]; ^~~~~~~~~~~~~~ UCLAMP_CNT include/linux/sched.h:277:2: note: 'UCLAMP_CNT' declared here
> 
> **Desktop (please complete the following information):**
> 
> * OS: centos7 linux5.4.54.

我这边在5.4.0-132-generic的内核版本上执行 sudo python3 ./get_loadavg.py 没有出现这样的报错，可以成果运行，如果可以的话，请你给我提供更多运行的细节。
或者如果仍然提示UCLAMP_BUCKETS没有被定义的话，你可以试着参照[eBPF_Supermarket/CPU_Subsystem/bpftrace_application/runqlen_se.c](https://github.com/linuxkerneltravel/lmp/blob/59901500abe528266347279bee8326e1d1d8b0b3/eBPF_Supermarket/CPU_Subsystem/bpftrace_application/runqlen_se.c#L61)中：
struct uclamp_rq {
	unsigned int value;
	struct uclamp_bucket bucket[5];
};
将UCLAMP_BUCKETS定义为5试着看可以运行不？
还有就是请确定你已经成功配置bcc环境
