### ISSUE TITLE
bpf 模板文件讨论

### ISSUE THREAD

**Issue by LinkinPF** [linuxkerneltravel/lmp#58]
bpf generator需要生成一个python文件和一个c文件，所以需要制定一个代码规范，方便generator的生成，这个每种指标的代码都不一样，有些是统一的，有些是私有的。大家可以针对自己写过的bcc代码，提出自己的想法或者模板，近期需要确定下来。

**Comment by a3323985** [comment]
dcstat和icstat这种统计需要计数的，一般会用到bpf_hash或者BPF_ARRAY，可以定义emnu类型的type，用于索引对应key，另外数据打印的时候也可以通过type循环打印指标，不用一一列出来，打印格式异常处理等设为一个模板。c部分可以单独定义几个功能函数，比如说计数的加减，类似指标多的时候每次只调用这个函数就行，命名格式也要统一。

biolacenty和syscount这种还需要定义命令行参数的，python的命令行定义可以统一，特别需要判断的，比如进程pid，通过if args.pid:text = ("#define FILTER_PID %d\n" % args.pid) + text  和#ifdef FILTER_PID这种方式实现。打印一般会用到两种b.trace_fields()和for k, v in sorted(data.items(), key=lambda kv: -kv[1].value)这种直接通过索引输出的，可以看提取什么指标分别俩模板。

也没有什么新发现，暂时就这点
