### ISSUE TITLE
eBPF DNS Cache

### ISSUE THREAD

**Issue by pengbinbin1** [linuxkerneltravel/lmp#581]
ebpf DNS Cache子项目中，我看ebpf部分代码只是解析出来了dns的请求数据包，然后返回了-1，那缓存这部分是在哪里实现的？用户态程序吗？另外，这个子项中readme中超链（基于ebpf的DNS Cache实现）接直接连到了开源之夏的首页（https://www.gitlink.org.cn/glcc/subjects/detail/257），有这个实现的详细连接可以分享吗，谢谢

**Comment by helight** [comment]
感谢，链接地址出错了，应该不需要这个链接地址，这个已经修复了

缓存是在内核中 ebpf 实现的。

**Comment by pengbinbin1** [comment]
> 感谢，链接地址出错了，应该不需要这个链接地址，这个已经修复了
> 
> 缓存是在内核中 ebpf 实现的。

在ebpf文件夹下的c文件中，我看到只是判断了一下dns的请求数据包就return -1了，具体是怎么实现的dns缓存呢？

**Comment by helight** [comment]
> > 感谢，链接地址出错了，应该不需要这个链接地址，这个已经修复了
> > 缓存是在内核中 ebpf 实现的。
> 
> 在ebpf文件夹下的c文件中，我看到只是判断了一下dns的请求数据包就return -1了，具体是怎么实现的dns缓存呢？

哦，是的，缓存在用户层，解析在内核层。main.rs 中有实现逻辑。

**Comment by pengbinbin1** [comment]
> > > 感谢，链接地址出错了，应该不需要这个链接地址，这个已经修复了
> > > 缓存是在内核中 ebpf 实现的。
> > 
> > 
> > 在ebpf文件夹下的c文件中，我看到只是判断了一下dns的请求数据包就return -1了，具体是怎么实现的dns缓存呢？
> 
> 哦，是的，缓存在用户层，解析在内核层。main.rs 中有实现逻辑。

内核态的ebpf程序判断到是DNS的请求数据包后，执行retrun -1，这个包是咋传到用户态里去的呢，可否详细解释一下，谢谢了

**Comment by pengbinbin1** [comment]
> > > > 感谢，链接地址出错了，应该不需要这个链接地址，这个已经修复了
> > > > 缓存是在内核中 ebpf 实现的。
> > > 
> > > 
> > > 在ebpf文件夹下的c文件中，我看到只是判断了一下dns的请求数据包就return -1了，具体是怎么实现的dns缓存呢？
> > 
> > 
> > 哦，是的，缓存在用户层，解析在内核层。main.rs 中有实现逻辑。
内核态的ebpf程序判断到是DNS的请求数据包后，执行retrun -1，这个包是咋传到用户态里去的呢，可否详细解释一下，谢谢了
