### ISSUE TITLE
[BUG]get_loadavg

### ISSUE THREAD

**Issue by pxp531** [linuxkerneltravel/lmp#635]
在get_load_avg.py文件中这个获取负载好像一直不准，是这份代码本身是不准的吗？我看了doc文档的解释，好像并没有解答我的疑惑。get_nr_running.py是获取处于running进程的数量吗？处于IO的是代表出于D状态的进程数量吗？这个项目有交流群吗

**Comment by helight** [comment]
这块是测试代码，负载相关的能力可以看这个项目https://github.com/linuxkerneltravel/lmp/tree/develop/eBPF_Supermarket/CPU_Subsystem/cpu_watcher
